# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x06sensor\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\"\x96\x01\n\x07IMUData\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x1e\n\x05\x61\x63\x63\x65l\x18\x02 \x01(\x0b\x32\x0f.sensor.Vector3\x12\x1d\n\x04gyro\x18\x03 \x01(\x0b\x32\x0f.sensor.Vector3\x12\'\n\x0borientation\x18\x04 \x01(\x0b\x32\x12.sensor.Quaternion\x12\x10\n\x08\x66rame_id\x18\x05 \x01(\t\"v\n\nCameraData\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x12\n\nimage_data\x18\x05 \x01(\x0c\x12\x10\n\x08\x66rame_id\x18\x06 \x01(\t\"v\n\nDepthImage\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x12\n\ndepth_data\x18\x05 \x01(\x0c\x12\x10\n\x08\x66rame_id\x18\x06 \x01(\t\"\x89\x01\n\rSensorMessage\x12\x1e\n\x03imu\x18\x01 \x01(\x0b\x32\x0f.sensor.IMUDataH\x00\x12$\n\x06\x63\x61mera\x18\x02 \x01(\x0b\x32\x12.sensor.CameraDataH\x00\x12#\n\x05\x64\x65pth\x18\x03 \x01(\x0b\x32\x12.sensor.DepthImageH\x00\x42\r\n\x0bsensor_datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR3']._serialized_start=24
  _globals['_VECTOR3']._serialized_end=66
  _globals['_QUATERNION']._serialized_start=68
  _globals['_QUATERNION']._serialized_end=124
  _globals['_IMUDATA']._serialized_start=127
  _globals['_IMUDATA']._serialized_end=277
  _globals['_CAMERADATA']._serialized_start=279
  _globals['_CAMERADATA']._serialized_end=397
  _globals['_DEPTHIMAGE']._serialized_start=399
  _globals['_DEPTHIMAGE']._serialized_end=517
  _globals['_SENSORMESSAGE']._serialized_start=520
  _globals['_SENSORMESSAGE']._serialized_end=657
# @@protoc_insertion_point(module_scope)
